<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca [
    <!ELEMENT biblioteca (libro+)>
    <!ELEMENT libro (titulo, autor, a単o, editorial)>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT autor (#PCDATA)>
    <!ELEMENT a単o (#PCDATA)>
    <!ELEMENT editorial (#PCDATA)>
]>

<biblioteca>
    <libro>
        <titulo></titulo>
        <autor></autor>
        <a単o></a単o>
        <editorial></editorial>
    </libro>
</biblioteca>