<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca [
    <!ELEMENT biblioteca (libro+)>
    <!ELEMENT libro (titulo, autor, anio)>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT autor (#PCDATA)>
    <!ELEMENT anio (#PCDATA)>
]>
<biblioteca>
    <libro>
        <titulo>El señor de los anillos</titulo>
        <autor>J.R.R. Tolkien</autor>
        <anio>1954</anio>
    </libro>
    <libro>
        <titulo>Cien años de soledad</titulo>
        <autor>Gabriel García Márquez</autor>
        <anio>1967</anio>
    </libro>
</biblioteca>